INSERT INTO MPARATE (name) VALUES ('G');
INSERT INTO MPARATE (name) VALUES ('PG');
INSERT INTO MPARATE (name) VALUES ('PG-13');
INSERT INTO MPARATE (name) VALUES ('R');
INSERT INTO MPARATE (name) VALUES ('NC-17');

INSERT INTO GENRES (name) VALUES ('Комедия');
INSERT INTO GENRES (name) VALUES ('Драма');
INSERT INTO GENRES (name) VALUES ('Мультфильм');
INSERT INTO GENRES (name) VALUES ('Триллер');
INSERT INTO GENRES (name) VALUES ('Документальный');
INSERT INTO GENRES (name) VALUES ('Боевик');
