CREATE TABLE IF NOT EXISTS MPARATE (
	id INTEGER PRIMARY KEY auto_increment, 
	name  VARCHAR(64)
);
CREATE TABLE IF NOT EXISTS FILMS (
	id INTEGER PRIMARY KEY auto_increment, 
	name  VARCHAR(64), 
	description VARCHAR, 
	releaseDate DATE, 
	duration LONG, 
	mparateId INTEGER,
 FOREIGN KEY (mparateId) REFERENCES MPARATE (id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS USERS (
	id INTEGER PRIMARY KEY auto_increment, 
	email VARCHAR(64), 
	login VARCHAR(64), 
	name VARCHAR(64), 
	birthday DATE
);
CREATE TABLE IF NOT EXISTS GENRES (
	id INTEGER PRIMARY KEY auto_increment, 
	name  VARCHAR(128)
);
CREATE TABLE IF NOT EXISTS LIKES (
	filmId INTEGER, 
	userId INTEGER,
 PRIMARY KEY (filmId,userId),
 FOREIGN KEY (filmId)  REFERENCES FILMS (id) ON DELETE CASCADE,
 FOREIGN KEY (userId)  REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS FRIENDS (
	userId INTEGER, 
	friendId INTEGER, 
	approved BOOLEAN,
 PRIMARY KEY (userId,friendId),
 FOREIGN KEY (userId)    REFERENCES USERS (id) ON DELETE CASCADE,
 FOREIGN KEY (friendId)  REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS FILMGENRES (
	filmId INTEGER, 
	genreId INTEGER,
 PRIMARY KEY (filmId,genreId),
 FOREIGN KEY (filmId)  REFERENCES FILMS (id) ON DELETE CASCADE,
 FOREIGN KEY (genreId)  REFERENCES GENRES (id) ON DELETE CASCADE
);
